### ISSUE TITLE
error on build script: " Repository '@hedron_compile_commands_pip' is not defined"

### ISSUE THREAD

**Issue by teletrail** [j20001970/GDMP#31] opened 2024-01-28 20:13 UTC
hi I get this error when attempting to build gdmp:

```(venv) (base) project@nanovac:/media/project/taskdisk/24.01/GDMP% python build.py desktop                     
ERROR: /media/project/taskdisk/24.01/GDMP/mediapipe/GDMP/desktop/BUILD:1:10: error loading package 'GDMP': at /home/project/.cache/bazel/_bazel_project/ab1d178f36bd2d9a03b46953fa4f356a/external/hedron_compile_commands/refresh_compile_commands.bzl:60:6: Unable to find package for @hedron_compile_commands_pip//:requirements.bzl: The repository '@hedron_compile_commands_pip' could not be resolved: Repository '@hedron_compile_commands_pip' is not defined. and referenced by '//GDMP/desktop:GDMP'
ERROR: Analysis of target '//GDMP/desktop:GDMP' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.060s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: GDMP
    Fetching repository @local_config_cc; starting
```

I am not sure how to resolve, any advice would be appreciated.

current system gentoo linux 64 bit with month-old software updates.

thanks.

**Comment by j20001970** [comment] 2024-02-07 04:21
Does it only happen on Gentoo? Could you try other distro to see if it happen as well?

**Comment by j20001970** [comment] 2024-02-08 17:27
I set up a Gentoo VM to test building GDMP and it build successfully. Could you provide more detail about your system, including Python and Bazel/Bazelisk version, and how do you install them.

Judging from the BUILD file path, does your system user have permission for the directory? You could also try putting GDMP source on home-relative location.

**Comment by j20001970** [comment] 2024-02-29 05:42
I was able to reproduce error message similar to yours by removing `hedron_compile_commands` defined in `mediapipe/WORKSPACE`, not sure why your message shows `hedron_compile_commands_pip` though.

There are a few thing you can check to troubleshoot your issue:

- Make sure `mediapipe/WORKSPACE` has been properly patched by `setup.py`
- Check python version, since you are on Gentoo I assume you are using newer version of python. If you are using python 3.12, try downgrading to 3.11.x.
- Simply clean bazel workspace and try again. Bazel command extractor is currently not pinned, maybe recent commits break something and you cloned it before it get fixed. I will pin it in upcoming update.

Closing for now, please reopen the issue if you have further questions.

**Closed by j20001970** 2024-02-29 05:42 UTC
